# Generated by Django 5.0 on 2024-11-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_farm_app', '0002_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='otp_verified',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
    ]
